### ISSUE TITLE
Configuration error when doing npm install

### ISSUE THREAD

**Issue by ShovanDhara** [yhagio/node-mongo-api-starter#1]
Please refer to the below screenshot. Every time when doing npm install, this error is showing. Please suggest any solution.

![capture](https://user-images.githubusercontent.com/3162504/52938674-3ccac000-3388-11e9-831b-5123e1dbc6ce.PNG)

**Comment by yhagio** [comment]
Oh this repo is old and not maintained, so probably many packages are deprecated.
I have fairly newer one here:
https://github.com/yhagio/mongo-express-starter
